export const FETCH_GENRES = 'FETCH_GENRES';
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIE_DETAILS = 'FETCH_MOVIE_DETAILS';
export const FETCH_MOVIES_BY_TITLE = 'FETCH_MOVIES_BY_TITLE';